### ISSUE TITLE
Base64 img

### ISSUE THREAD

**Issue by Paroxyste** [Miksus/red-mail#15]
Hello, first of all thank you for this insane package.

I would like to add an image in base64 format in a `<img src="{{ my_image_b64 }}" class="" /> `using `body_images = {}`

Is this possible? 

If yes can you show me an example, my image is a string in base64 format (`data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAA ....` )

Thanks a lot

**Comment by Miksus** [comment]
Hi, thanks! It's always nice to hear people like it. 

I think it should be possible, for example, see this:
```python
from redmail import gmail

gmail.user_name = "..."
gmail.password = "..."

# A red dot as base64 found from Wikipedia:
data_as_base64 = 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=='

import base64
gmail.send(
    subject='An example',
    receivers=['something@example.com'],
    html='<h1>This is an image:</h1> {{ myimage }}',
    body_images={ 
        'myimage': base64.b64decode(data_as_base64)
    }
)
```
However, I realized due to a slightly stupid mistake, I had not built support for other than PNG. My aim was to allow one to define it exactly if they passed a dictionary, like:
```python
gmail.send(
    subject='An example',
    receivers=['something@example.com'],
    html='<h1>This is an image:</h1> {{ myimage }}',
    body_images={ 
        'myimage': {
            'content': base64.b64decode(data_as_base64),
            'maintype': 'image',
            'subtype': 'jpg',
    }
)
```
but I slightly messed it up: https://github.com/Miksus/red-mail/blob/master/redmail/email/body.py#L200 and has stupidly PNG hardcoded. It seems I only worked and tested with PNGs but it seems it's pretty easy to fix. I'll try to release a patch that fixes this latest next week.

Thanks for bringing this up!

**Comment by Paroxyste** [comment]
Thank you for your quick response, I have tested your examples and it works great. Thanks again for this package.
